# Makefile for Win32

!include <win32.mak>

TOP  = ../..
SRCS = bigtest.c cursor_test.c over_test.c shape_test.c test1.c test10.c test11.c test12.c test13.c test14.c test15.c test16.c test17.c test18.c test19.c test2.c test20.c test21.c test22.c test23.c test24.c test3.c test4.c test5.c test6.c test7.c test8.c test9.c timer_test.c test25.c

!include "$(TOP)/glutwin32.mak"
